Repository QuantStack/jupyterlab-blockly, pull requests merged in 2022-06, with the labels that each got.

#18 initial code for changing the language
  src/factory.ts
  src/index.ts
  src/layout.ts
  src/manager.ts
  src/widget.ts
Labels: enhancement

#20 FileType, Manager and Register
  .eslintignore
  .eslintrc.js
  .github/workflows/binder-on-pr.yml
  .pre-commit-config.yaml
  .prettierrc
  README.md
  RELEASE.md
  package.json
  patches/@jupyterlab+codeeditor+3.4.3.patch
  src/factory.ts
  src/index.ts
  src/layout.ts
  src/manager.ts
  src/registry.ts
  src/token.ts
  src/toolbar/index.ts
  src/toolbar/selector.tsx
  src/toolbar/utils.ts
  src/widget.ts
  style/base.css
  tsconfig.json
  yarn.lock
Labels: documentation, enhancement, maintenance

#22 Automated Changelog Entry for 0.1.0a1 on main
  CHANGELOG.md
Labels: documentation

#24 Adds a dropdown to select a toolbox
  src/index.ts
  src/layout.ts
  src/manager.ts
  src/niryo/niryo_one_python_generators.js
  src/toolbar/generator.tsx
  src/toolbar/index.ts
  src/toolbar/toolbox.tsx
  src/widget.ts
  tsconfig.json
Labels: enhancement

#29 Automated Changelog Entry for 0.1.0a2 on main
  CHANGELOG.md
Labels: documentation
