Repository QuantStack/jupyterlab-blockly, pull requests merged in 2022-07, with the labels that each got.

#30 add checks for top level initializations of blocks
  src/layout.ts
Labels: enhancement

#36 Register fileType jpblockly in jupyterLite
  docs/jupyter-lite.json
Labels: bug, documentation

#39 Embed jupyterlite into index page
  docs/index.rst
Labels: documentation

#40 Fixes package.json path
  jupyterlab_blockly/_version.py
Labels: bug

#42 Update release documentation
  .eslintignore
  .prettierignore
  RELEASE.md
  assets/info_full_release.png
  assets/merge_changelog.png
  assets/run_draft_changelog.png
  assets/run_full_release.png
  pyproject.toml
Labels: documentation, enhancement

#44 Remove unused imports
  docs/conf.py
Labels: documentation

#45 Switch to `environment.yml` for the docs
  .readthedocs.yml
  docs/environment.yml
  docs/requirements.txt
Labels: documentation, enhancement

#47 Adds jupyterlab-blockly and blockly into the extension bundle
  packages/blockly-extension/package.json
Labels: enhancement

#50 Include packages
  jupyterlab_blockly/_version.py
Labels: bug, maintenance

#51 Automated Changelog Entry for 0.1.0a5 on main
  CHANGELOG.md
Labels: documentation

#58 Automated Changelog Entry for 0.1.0 on main
  CHANGELOG.md
Labels: documentation

#59 Updated docs for other extensions category
  docs/other_extensions.md
  packages/blockly/src/registry.ts
Labels: documentation

#60 Kernels in JupyterLite
  docs/environment.yml
  docs/jupyter-lite.json
  docs/jupyterlite_config.json
Labels: bug, documentation

#61 Add blockly
  docs/jupyterlite_config.json
Labels: bug, documentation
