Repository QuantStack/jupyterlab-blockly, pull requests merged in 2024-08, with the labels that each got.

#85 Migrate to JupyterLab 4
  .eslintignore
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/enforce-label.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .gitignore
  .prettierignore
  .yarnrc.yml
  LICENSE
  README.md
  RELEASE.md
  binder/environment.yml
  docs/conf.py
  docs/installation.md
  jupyterlab_blockly/__init__.py
  package.json
  packages/blockly-extension/package.json
  packages/blockly-extension/src/index.ts
  packages/blockly-extension/src/svg.d.ts
  packages/blockly-extension/webpack.config.js
  packages/blockly/package.json
  packages/blockly/src/factory.ts
  packages/blockly/src/layout.ts
  packages/blockly/src/registry.ts
  packages/blockly/src/widget.ts
  patches/@jupyterlab+codeeditor+3.6.3.patch
  pyproject.toml
  scripts/bump-version.py
  tsconfig.json
  yarn.lock
Labels: enhancement

#86 Fix Binder configuration
  .eslintignore
  .github/workflows/binder-on-pr.yml
  .prettierignore
  LICENSE
  README.md
  binder/environment.yml
  binder/postBuild
  package.json
  pyproject.toml
  yarn.lock
Labels: bug

#87 Update JupyterLite deployment and docs
  docs/build-environment.yml
  docs/conf.py
  docs/other_extensions.md
Labels: enhancement

#88 Update release information
  RELEASE.md
Labels: documentation

#89 Restore `bump-version` script
  pyproject.toml
  scripts/bump-version.py
Labels: bug

#91 Fix `Blockly` language for default locale
  packages/blockly-extension/src/index.ts
Labels: bug

#90 Update Lite deployment
  docs/build-environment.yml
  docs/conf.py
  docs/other_extensions.md
Labels: bug, documentation

#99 Update docs
  docs/installation.md
  docs/other_extensions.md
Labels: documentation

#100 Generate _version.py at build time
  .gitignore
  jupyterlab_blockly/_version.py
  pyproject.toml
Labels: bug

#101 Update `jupyter-widgets` dependencies
  packages/blockly-extension/package.json
  yarn.lock
Labels: maintenance
